/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Album;
import BackEnd.DataBase;
import BackEnd.Singer;
import BackEnd.Song;
import BackEnd.User;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EYMEN
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    DataBase db = new DataBase();
    DefaultTableModel model;
    DefaultTableModel model2;
    DefaultTableModel model3;
    DefaultTableModel model4;

    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) songtable.getModel();
        model2 = (DefaultTableModel) singertable.getModel();
        model3 = (DefaultTableModel) usertable.getModel();
        model4 = (DefaultTableModel) albumtable.getModel();
        sarkiListele();
        sanatciListele();
        kullaniciListele();
        albumListele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        singertable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        songtable = new javax.swing.JTable();
        songekle = new javax.swing.JButton();
        songguncelle = new javax.swing.JButton();
        songsil = new javax.swing.JButton();
        sanatciekle = new javax.swing.JButton();
        sanatciguncelle = new javax.swing.JButton();
        sanatcisil = new javax.swing.JButton();
        userekle = new javax.swing.JButton();
        userguncelle = new javax.swing.JButton();
        usersil = new javax.swing.JButton();
        adso = new javax.swing.JTextField();
        tarihso = new javax.swing.JTextField();
        alb_idso = new javax.swing.JTextField();
        turso = new javax.swing.JTextField();
        sureso = new javax.swing.JTextField();
        dinlenmeso = new javax.swing.JTextField();
        sanatciad = new javax.swing.JTextField();
        sanatciulke = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        sifre = new javax.swing.JTextField();
        ulke = new javax.swing.JTextField();
        abonelik = new javax.swing.JTextField();
        sarkimesaj = new javax.swing.JLabel();
        usermesaj = new javax.swing.JLabel();
        sarkicimesaj = new javax.swing.JLabel();
        userad = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        albumtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sanid = new javax.swing.JTextField();
        sarid = new javax.swing.JTextField();
        tur = new javax.swing.JTextField();
        tarih = new javax.swing.JTextField();
        albname = new javax.swing.JTextField();
        albummesaj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        singertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "ülke"
            }
        ));
        singertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(singertable);

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "email", "şifre", "ülke", "abonelik"
            }
        ));
        usertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(usertable);

        songtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "tarih", "alb_id", "tür", "süre", "dinlenme"
            }
        ));
        songtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                songtableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(songtable);

        songekle.setText("add");
        songekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        songekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songekleActionPerformed(evt);
            }
        });

        songguncelle.setText("update");
        songguncelle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        songguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songguncelleActionPerformed(evt);
            }
        });

        songsil.setText("delete");
        songsil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        songsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songsilActionPerformed(evt);
            }
        });

        sanatciekle.setText("add");
        sanatciekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sanatciekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciekleActionPerformed(evt);
            }
        });

        sanatciguncelle.setText("update");
        sanatciguncelle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sanatciguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatciguncelleActionPerformed(evt);
            }
        });

        sanatcisil.setText("delete");
        sanatcisil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sanatcisil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatcisilActionPerformed(evt);
            }
        });

        userekle.setText("add");
        userekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userekleActionPerformed(evt);
            }
        });

        userguncelle.setText("update");
        userguncelle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userguncelleActionPerformed(evt);
            }
        });

        usersil.setText("delete");
        usersil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersilActionPerformed(evt);
            }
        });

        tarihso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihsoActionPerformed(evt);
            }
        });

        sarkimesaj.setForeground(new java.awt.Color(255, 51, 51));

        usermesaj.setForeground(new java.awt.Color(255, 51, 51));

        sarkicimesaj.setForeground(new java.awt.Color(255, 51, 51));

        userad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useradActionPerformed(evt);
            }
        });

        albumtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "sanatci_id", "sarki_id", "tarih", "tür"
            }
        ));
        albumtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumtableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(albumtable);

        jButton1.setText("add");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("update");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("delete");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("songs");

        jLabel2.setText("singers");

        jLabel3.setText("albums");

        jLabel4.setText("users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarihso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alb_idso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(turso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sureso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dinlenmeso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(userad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abonelik, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usermesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sanatciekle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sanatciguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sanatcisil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userekle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usersil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(161, 161, 161)
                                .addComponent(sanatciad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(sanatciulke, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(songekle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(songguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(songsil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sarkimesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sarkicimesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(49, 49, 49)
                            .addComponent(albname, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sanid, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sarid, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tur, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(albummesaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sanatciad, sanatciulke});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {abonelik, email, sifre, ulke, userad});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adso, alb_idso, dinlenmeso, sureso, tarihso, turso});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sarkimesaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tarihso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alb_idso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(turso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sureso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dinlenmeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(songekle)
                        .addGap(18, 18, 18)
                        .addComponent(songguncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(songsil))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(sarkicimesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sanatciad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sanatciulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sanatciekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sanatciguncelle)
                        .addGap(18, 18, 18)
                        .addComponent(sanatcisil))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sanid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(albname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(albummesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(abonelik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usermesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userekle)
                        .addGap(18, 18, 18)
                        .addComponent(userguncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usersil))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarihsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihsoActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void sanatciguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciguncelleActionPerformed
        // TODO add your handling code here:
        int selectedrow = singertable.getSelectedRow();
        int id = (int) singertable.getValueAt(selectedrow, 0);
        String ad = this.sanatciad.getText();
        String ulke = this.sanatciulke.getText();
        if (selectedrow == -1) {
            if (selectedrow == 0) {
                sarkicimesaj.setText("sanatçı yok");
            } else {
                sarkicimesaj.setText("sanatçı seç");
            }
        } else {
            sarkicimesaj.setText("sanatçı güncellendi");
            db.sanatciGuncelle(id, ad, ulke);
            this.sanatciListele();
        }

    }//GEN-LAST:event_sanatciguncelleActionPerformed

    private void songekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songekleActionPerformed
        // TODO add your handling code here:
        //int id=Integer.valueOf(this.idso.getText());
        String ad = this.adso.getText();
        String tarih = this.tarihso.getText();
        String alb_id = this.alb_idso.getText();
        String tur = this.turso.getText();
        float sure = Float.valueOf(this.sureso.getText());
        String dinlenme = this.dinlenmeso.getText();
        db.sarkiEkle(ad, tarih, alb_id, tur, sure, dinlenme);
        this.sarkiListele();
    }//GEN-LAST:event_songekleActionPerformed

    private void songtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_songtableMouseClicked
        // TODO add your handling code here:
        int selectedrow = songtable.getSelectedRow();

        this.adso.setText((String) model.getValueAt(selectedrow, 1));
        this.tarihso.setText((String) model.getValueAt(selectedrow, 2));
        this.alb_idso.setText((String) model.getValueAt(selectedrow, 3));
        this.turso.setText((String) model.getValueAt(selectedrow, 4));
        this.sureso.setText((String) model.getValueAt(selectedrow, 5));
        this.dinlenmeso.setText((String) model.getValueAt(selectedrow, 6));

    }//GEN-LAST:event_songtableMouseClicked

    private void songguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songguncelleActionPerformed
        // TODO add your handling code here:
        int selectedrow = this.songtable.getSelectedRow();
        String ad = this.adso.getText();
        String tarih = this.tarihso.getText();
        String alb_id = this.alb_idso.getText();
        String tur = this.turso.getText();
        float sure = Float.valueOf(this.sureso.getText());
        String dinlenme = this.dinlenmeso.getText();
        int id = (int) songtable.getValueAt(selectedrow, 0);
        if (selectedrow == -1) {
            if (selectedrow == 0) {
                sarkimesaj.setText("sarki yok");
            } else {
                sarkimesaj.setText("sarki sec");
            }
        } else {
            sarkimesaj.setText("guncellendi");
            db.sarkiGuncelle(id, ad, tarih, alb_id, tur, sure, dinlenme);
            this.sarkiListele();
        }
    }//GEN-LAST:event_songguncelleActionPerformed

    private void songsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songsilActionPerformed
        // TODO add your handling code here:
        int selectedrow = this.songtable.getSelectedRow();
        int id = (int) songtable.getValueAt(selectedrow, 0);
        if (selectedrow == -1) {
            if (selectedrow == 0) {
                sarkimesaj.setText("şarkı yok");
            } else {
                sarkimesaj.setText("şarkı seç");
            }
        } else {
            sarkimesaj.setText("şarkı silindi");
            db.sarkiSil(id);
            this.sarkiListele();
        }
    }//GEN-LAST:event_songsilActionPerformed

    private void sanatciekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatciekleActionPerformed
        // TODO add your handling code here:
        String ad = this.sanatciad.getText();
        String ulke = this.sanatciulke.getText();
        db.sanatciEkle(ad, ulke);
        this.sanatciListele();
        sarkicimesaj.setText("şarkıcı eklendi");
    }//GEN-LAST:event_sanatciekleActionPerformed

    private void singertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singertableMouseClicked
        // TODO add your handling code here:
        int selectedrow = singertable.getSelectedRow();
        this.sanatciad.setText((String) singertable.getValueAt(selectedrow, 1));
        this.sanatciulke.setText((String) singertable.getValueAt(selectedrow, 2));
    }//GEN-LAST:event_singertableMouseClicked

    private void sanatcisilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatcisilActionPerformed
        // TODO add your handling code here:
        int selectedrow = singertable.getSelectedRow();
        int id = (int) singertable.getValueAt(selectedrow, 0);
        db.sanatciSil(id);
        this.sanatciListele();
        sarkicimesaj.setText("şarkıcı silindi");
    }//GEN-LAST:event_sanatcisilActionPerformed

    private void usertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertableMouseClicked
        // TODO add your handling code here:
        int selectedrow = usertable.getSelectedRow();
        this.userad.setText((String) usertable.getValueAt(selectedrow, 1));
        this.email.setText((String) usertable.getValueAt(selectedrow, 2));
        this.sifre.setText((String) usertable.getValueAt(selectedrow, 3));
        this.ulke.setText((String) usertable.getValueAt(selectedrow, 4));
        abonelik.setText(usertable.getValueAt(selectedrow, 5).toString());


    }//GEN-LAST:event_usertableMouseClicked

    private void userekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userekleActionPerformed
        // TODO add your handling code here:
        String ad = this.userad.getText();
        String email = this.email.getText();
        String sifre = this.sifre.getText();
        String country = this.ulke.getText();
        int abonelik = Integer.valueOf(this.abonelik.getText());
        db.kullaniciEkle(ad, email, sifre, country, abonelik);
        this.kullaniciListele();
        usermesaj.setText("kullanıcı eklendi");
    }//GEN-LAST:event_userekleActionPerformed

    private void userguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userguncelleActionPerformed
        // TODO add your handling code here:
        int selectedrow = usertable.getSelectedRow();
        int id = (int) usertable.getValueAt(selectedrow, 0);
        String ad = this.userad.getText();
        String email = this.email.getText();
        String password = this.sifre.getText();
        String country = this.ulke.getText();
        int abonelik = Integer.valueOf(this.abonelik.getText());
        if (selectedrow == -1) {
            if (selectedrow == 0) {
                usermesaj.setText("kullanıcı yok");
            } else {
                usermesaj.setText("kullanıcı seç");
            }
        } else {
            db.userGuncelle(id, ad, email, password, country, abonelik);
            this.kullaniciListele();
            usermesaj.setText("kullanıcı güncellendi");
        }
    }//GEN-LAST:event_userguncelleActionPerformed

    private void usersilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersilActionPerformed
        // TODO add your handling code here:
        int selectedrow = this.usertable.getSelectedRow();
        int id = (int) this.usertable.getValueAt(selectedrow, 0);
        db.kullaniciSil(id);
        this.kullaniciListele();
    }//GEN-LAST:event_usersilActionPerformed

    private void useradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useradActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.usermesaj.setText("user silindi");
        String albad=this.albname.getText();
        String sanid=this.sanid.getText();
        String sarid=this.sarid.getText();
        String tarih=this.tarih.getText();
        String tur=this.tur.getText();
        db.albumEkle(albad,sanid,sarid,tarih,tur);
        this.albumListele();
        
                
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void albumtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumtableMouseClicked
        // TODO add your handling code here:
        int selectedrow=this.albumtable.getSelectedRow();
        this.albname.setText((String) model4.getValueAt(selectedrow, 1));
        this.sanid.setText((String) albumtable.getValueAt(selectedrow, 2));
        this.sarid.setText((String) albumtable.getValueAt(selectedrow, 3));
        this.tarih.setText((String) albumtable.getValueAt(selectedrow, 4));
        this.tur.setText((String) albumtable.getValueAt(selectedrow, 5));

    }//GEN-LAST:event_albumtableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedrow=albumtable.getSelectedRow();
        int id=(int) albumtable.getValueAt(selectedrow, 0);
        db.albumSil(id);
        this.albummesaj.setText("album silindi");
        this.albumListele();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedrow=this.albumtable.getSelectedRow();
        int id=(int) this.albumtable.getValueAt(selectedrow, 0);
        String ad=this.albname.getText();
        String sanid=this.sanid.getText();
        String sarid=this.sarid.getText();
        String tarih=this.tarih.getText();
        String tur=this.tur.getText();
        db.albumGuncelle(id,ad,sanid,sarid,tarih,tur);
        this.albumListele();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abonelik;
    private javax.swing.JTextField adso;
    private javax.swing.JTextField alb_idso;
    private javax.swing.JTextField albname;
    private javax.swing.JLabel albummesaj;
    private javax.swing.JTable albumtable;
    private javax.swing.JTextField dinlenmeso;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField sanatciad;
    private javax.swing.JButton sanatciekle;
    private javax.swing.JButton sanatciguncelle;
    private javax.swing.JButton sanatcisil;
    private javax.swing.JTextField sanatciulke;
    private javax.swing.JTextField sanid;
    private javax.swing.JTextField sarid;
    private javax.swing.JLabel sarkicimesaj;
    private javax.swing.JLabel sarkimesaj;
    private javax.swing.JTextField sifre;
    private javax.swing.JTable singertable;
    private javax.swing.JButton songekle;
    private javax.swing.JButton songguncelle;
    private javax.swing.JButton songsil;
    private javax.swing.JTable songtable;
    private javax.swing.JTextField sureso;
    private javax.swing.JTextField tarih;
    private javax.swing.JTextField tarihso;
    private javax.swing.JTextField tur;
    private javax.swing.JTextField turso;
    private javax.swing.JTextField ulke;
    private javax.swing.JTextField userad;
    private javax.swing.JButton userekle;
    private javax.swing.JButton userguncelle;
    private javax.swing.JLabel usermesaj;
    private javax.swing.JButton usersil;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables

    private void sarkiListele() {
        model.setRowCount(0);
        ArrayList<Song> sn = new ArrayList<Song>();
        sn = db.sarkiGetir();
        if (sn != null) {
            for (Song s : sn) {
                Object ekle[] = {s.getId(), s.getAd(), s.getTarih(), s.getAlb_id(), s.getTür(), s.getSüre(), s.getDinlenme()};
                model.addRow(ekle);
            }
        }

    }

    private void sanatciListele() {
        model2.setRowCount(0);
        ArrayList<Singer> singers = new ArrayList<Singer>();
        singers = db.sanatciGetir();
        if (singers != null) {
            for (Singer sn : singers) {
                Object[] sanatci = {sn.getId(), sn.getAd(), sn.getUlke()};
                model2.addRow(sanatci);
            }

        }
    }

    private void kullaniciListele() {
        model3.setRowCount(0);
        ArrayList<User> users = new ArrayList<User>();
        users = db.kullaniciGetir();
        if (users != null) {
            for (User us : users) {
                Object kullanici[] = {us.getId(), us.getName(), us.getEmail(), us.getPassword(), us.getCountry(), us.getAbonelik()};//obje dizisine kullanıcıdaki 
                //elemanları alıyoruz bu çok önemli
                model3.addRow(kullanici);
            }

        }
    }

    private void albumListele() {
        model4.setRowCount(0);
        ArrayList<Album> al = new ArrayList<Album>();
        al = db.albumAl();
        if (al != null) {
            for (Album als : al) {
                Object albums [] ={als.getId(),als.getName(),als.getSanatci_id(),als.getSarki_id(),als.getTarih(),als.getTur()};//obje dizisi
                model4.addRow(albums);
            }
        }
    }
}
