/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.DataBase;
import BackEnd.Song;
import BackEnd.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EYMEN
 */
public class PremiumUser extends javax.swing.JFrame {

    /**
     * Creates new form PremiumUser
     */
    DefaultTableModel model1 = new DefaultTableModel();
    DataBase db = new DataBase();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultTableModel model3 = new DefaultTableModel();
    DefaultTableModel model4 = new DefaultTableModel();
    DefaultTableModel model5 = new DefaultTableModel();
    String email;
    String femail;

    public PremiumUser() {

    }

    PremiumUser(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pruser.setText(user.getEmail());
        email = user.getEmail();

        //db.premiumAl(email);
        model1 = (DefaultTableModel) premiumusers.getModel();
        model2 = (DefaultTableModel) songs.getModel();
        model3 = (DefaultTableModel) popl.getModel();
        model4 = (DefaultTableModel) jazzl.getModel();
        model5 = (DefaultTableModel) classicl.getModel();
        songsListele(email);
        pUserListele();
        userPopListele(email);
        userJazzListele(email);
        userClassicListele(email);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pruser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listeler = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        songs = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        popl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        premiumusers = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        classicl = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jazzl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        uyari = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        followed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pruser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pruser.setForeground(new java.awt.Color(51, 204, 255));
        pruser.setText("user");

        jLabel1.setText("premium users");

        listeler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pop", "jazz", "classic" }));

        jButton1.setText("followed users");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        songs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "tür", "dinlenme"
            }
        ));
        songs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        songs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                songsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(songs);

        jButton2.setText("add song");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        popl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "dinlenme"
            }
        ));
        jScrollPane3.setViewportView(popl);

        jLabel3.setText("playlists");

        jButton4.setText("songs");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("top10");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        premiumusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "email", "ülke", "abonelik"
            }
        ));
        premiumusers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        premiumusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premiumusersMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(premiumusers);

        jLabel5.setText("my songs");

        classicl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "dinlenme"
            }
        ));
        jScrollPane4.setViewportView(classicl);

        jazzl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "dinlenme"
            }
        ));
        jScrollPane6.setViewportView(jazzl);

        jLabel6.setText("pop");

        jLabel7.setText("jazz");

        jLabel8.setText("classic");

        jButton3.setText("view");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("listen as you wish");

        uyari.setForeground(new java.awt.Color(255, 51, 51));
        uyari.setText("add a song");

        jButton6.setText("albums");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("follow");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        followed.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(pruser)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(91, 91, 91)
                                                        .addComponent(jLabel9))
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(354, 354, 354)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(followed, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(listeler, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8))
                                .addGap(71, 71, 71)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pruser)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(followed, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(listeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uyari)
                            .addGap(6, 6, 6))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void premiumusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premiumusersMouseClicked
        // TODO add your handling code here:
//        int selectedrow = premiumusers.getSelectedRow();
//        this.userad.setText((String) premiumusers.getValueAt(selectedrow, 1));
//        this.email.setText((String) premiumusers.getValueAt(selectedrow, 2));
//        this.sifre.setText((String) premiumusers.getValueAt(selectedrow, 3));
//        this.ulke.setText((String) premiumusers.getValueAt(selectedrow, 4));
//        abonelik.setText(premiumusers.getValueAt(selectedrow, 5).toString());

    }//GEN-LAST:event_premiumusersMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //emaili çekip constructora atıyoruz ardından orada kullanıyoruz
        String email = this.pruser.getText();
        Songs song = new Songs(new User(email));//user
        song.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Top10 t = new Top10(new User(email));
        t.setVisible(true);


    }//GEN-LAST:event_jButton5ActionPerformed

    private void songsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_songsMouseClicked
        // TODO add your handling code here:
        int selectedrow = songs.getSelectedRow();
        String name = (String) songs.getValueAt(selectedrow, 0);
        String dinlenme = String.valueOf(songs.getValueAt(selectedrow, 2));
        int tiklama = Integer.parseInt(dinlenme);
        tiklama++;
        db.dinlenmeSayisi(name, tiklama);
        db.ldinlenmeSayisi(name, tiklama);
        db.sdinlenmeSayisi(name, tiklama);
        JOptionPane.showMessageDialog(this, name + " dinleniyor");
        songs.setValueAt(tiklama, selectedrow, 2);

        this.userClassicListele(email);
        this.userJazzListele(email);
        this.userPopListele(email);


    }//GEN-LAST:event_songsMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedrow = songs.getSelectedRow();
        System.out.println(selectedrow);
        String sarkiAdi = null;
        int dinlenme = 0;
        String turAl = null;
        if (selectedrow == -1) {
            this.uyari.setText("seçim yapiniz");
        } else {
            sarkiAdi = (String) songs.getValueAt(selectedrow, 0);
            dinlenme = (int) songs.getValueAt(selectedrow, 2);
            turAl = (String) this.songs.getValueAt(selectedrow, 1);
        }
        if (listeler.getSelectedIndex() == 0) {

            if (turAl.equals("pop")) {
                //popa ekle
                System.out.println(email);
                if (listemdeMi(email, sarkiAdi)) {
                    this.uyari.setText("şarkı listenizde var");
                } else {
                    db.calmaList(email, dinlenme, turAl, sarkiAdi);
                    this.userPopListele(email);
                    this.uyari.setText("popa eklendi");
                }
            } else {
                uyari.setText("wrong genre");
            }

        } else if (listeler.getSelectedItem().equals("jazz")) {

            if (turAl.equals("jazz")) {
                //jazz işlemleri
                System.out.println(email);
                if (listemdeMi(email, sarkiAdi)) {
                    this.uyari.setText("şarkı listenizde var");
                } else {
                    db.calmaList(email, dinlenme, turAl, sarkiAdi);
                    this.userJazzListele(email);
                    this.uyari.setText("jazza eklendi");
                }
            } else {
                uyari.setText("wrong genre");
            }
        } else if (listeler.getSelectedItem().equals("classic")) {

            if (turAl.equals("classic")) {
                //classic işlemleri
                System.out.println(email);
                if (listemdeMi(email, sarkiAdi)) {
                    this.uyari.setText("şarkı listenizde var");
                } else {
                    db.calmaList(email, dinlenme, turAl, sarkiAdi);
                    this.userClassicListele(email);
                    this.uyari.setText("classice eklendi");
                }
            } else {
                uyari.setText("wrong genre");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.out.println(email);
        FollowedUsersScreen fu = new FollowedUsersScreen(new User(email));
        fu.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //kullanıcı takip etme işlemlerini yapalım...
        int selectedrow = this.premiumusers.getSelectedRow();

        if (selectedrow == -1) {
            followed.setText("kullanici seçiniz.");
        } else {
            femail = (String) premiumusers.getValueAt(selectedrow, 2);
            if (takipEdildiMi()) {
                System.out.println(femail);
                FollowedScreen f = new FollowedScreen(new User(email), new User(femail));
                this.setVisible(false);
                f.setVisible(true);
            } else {
                followed.setText("lütfen önce takip ediniz.");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedrow = this.premiumusers.getSelectedRow();

        if (selectedrow == -1) {
            followed.setText("kullanici seçiniz");
        } else {
            femail = (String) premiumusers.getValueAt(selectedrow, 2);
            if (takipciMi()) {
                this.followed.setText(femail + " zaten takip ediliyor");
            } else {
                System.out.println(femail);
                db.followerOl(email, femail);
                this.followed.setText(femail + " takip ediliyor");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AlbumScreen alb=new AlbumScreen(new User(email));
        alb.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PremiumUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PremiumUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PremiumUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PremiumUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PremiumUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable classicl;
    private javax.swing.JLabel followed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jazzl;
    private javax.swing.JComboBox<String> listeler;
    private javax.swing.JTable popl;
    private javax.swing.JTable premiumusers;
    public javax.swing.JLabel pruser;
    private javax.swing.JTable songs;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables

    private void pUserListele() {
        model1.setRowCount(0);
        ArrayList<User> user = new ArrayList<User>();
        user = db.premiumlarAl();
        if (user != null) {
            for (User us : user) {
                Object[] ekle = {us.getId(), us.getName(), us.getEmail(), us.getCountry(), us.getAbonelik()};
                model1.addRow(ekle);
            }
        }
    }

    private void songsListele(String email) {//metoda atmak önemli :)))))
        model2.setRowCount(0);
        ArrayList<Song> s = new ArrayList<Song>();
        s = db.userSarkiAl(email);
        if (s != null) {
            for (Song songs : s) {
                String[] eklee = {songs.getAd(), songs.getTür(), songs.getDinlenme()};
                model2.addRow(eklee);
            }

        }
    }

    private void userPopListele(String email) {
        model3.setRowCount(0);
        ArrayList<Song> song = new ArrayList<Song>();
        song = db.userPopAl(email);
        if (song != null) {
            for (Song songs : song) {
                Object add[] = {songs.getAd(), songs.getDinlenme()};
                model3.addRow(add);
            }

        }
    }

    private void userJazzListele(String email) {
        model4.setRowCount(0);
        ArrayList<Song> song = new ArrayList<Song>();
        song = db.userJazzAl(email);
        if (song != null) {
            for (Song songs : song) {
                Object add[] = {songs.getAd(), songs.getDinlenme()};
                model4.addRow(add);
            }

        }
    }

    private void userClassicListele(String email) {
        model5.setRowCount(0);
        ArrayList<Song> song = new ArrayList<Song>();
        song = db.userClassicAl(email);
        if (song != null) {
            for (Song songs : song) {
                Object add[] = {songs.getAd(), songs.getDinlenme()};
                model5.addRow(add);
            }
        }
    }

    private boolean takipEdildiMi() {
        if (db.followerMi(email, femail)) {
            return true;
        } else {
            return false;
        }
    }

    private boolean takipciMi() {
        if (db.zatenTakipci(email, femail)) {
            return true;
        } else {
            return false;
        }
    }

    private boolean listemdeMi(String email, String sarkiAdi) {
        if (db.sarkiListemde(sarkiAdi, email)) {
            return true;
        } else {
            return false;
        }
    }

}
